name: 'Continuous Delivery'

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Build and Push Docker image to Artifact Registry
        run: |-
          gcloud builds submit . --tag southamerica-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/latam-challenge-repo/flight-delay-api:latest

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy flight-delay-api \
            --image southamerica-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/latam-challenge-repo/flight-delay-api:latest \
            --platform managed \
            --region southamerica-west1 \
            --allow-unauthenticated \
            --port 8080